// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dsp/v1alpha2/control.proto

// Protobuf Java Version: 3.25.3
package com.dsp.v1alpha2;

/**
 * <pre>
 * ContractTerminateRequest contains the pid, code, and reason of the contract negotiation to terminate.
 * </pre>
 *
 * Protobuf type {@code dsp.v1alpha2.ContractTerminateRequest}
 */
public final class ContractTerminateRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dsp.v1alpha2.ContractTerminateRequest)
    ContractTerminateRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ContractTerminateRequest.newBuilder() to construct.
  private ContractTerminateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ContractTerminateRequest() {
    pid_ = "";
    code_ = "";
    reason_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new ContractTerminateRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ControlProto.internal_static_dsp_v1alpha2_ContractTerminateRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ControlProto.internal_static_dsp_v1alpha2_ContractTerminateRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ContractTerminateRequest.class, Builder.class);
  }

  public static final int PID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile Object pid_ = "";
  /**
   * <code>string pid = 1 [json_name = "pid"];</code>
   * @return The pid.
   */
  @Override
  public String getPid() {
    Object ref = pid_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      pid_ = s;
      return s;
    }
  }
  /**
   * <code>string pid = 1 [json_name = "pid"];</code>
   * @return The bytes for pid.
   */
  @Override
  public com.google.protobuf.ByteString
      getPidBytes() {
    Object ref = pid_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      pid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CODE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile Object code_ = "";
  /**
   * <code>string code = 2 [json_name = "code"];</code>
   * @return The code.
   */
  @Override
  public String getCode() {
    Object ref = code_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      code_ = s;
      return s;
    }
  }
  /**
   * <code>string code = 2 [json_name = "code"];</code>
   * @return The bytes for code.
   */
  @Override
  public com.google.protobuf.ByteString
      getCodeBytes() {
    Object ref = code_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      code_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REASON_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList reason_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string reason = 3 [json_name = "reason"];</code>
   * @return A list containing the reason.
   */
  public com.google.protobuf.ProtocolStringList
      getReasonList() {
    return reason_;
  }
  /**
   * <code>repeated string reason = 3 [json_name = "reason"];</code>
   * @return The count of reason.
   */
  public int getReasonCount() {
    return reason_.size();
  }
  /**
   * <code>repeated string reason = 3 [json_name = "reason"];</code>
   * @param index The index of the element to return.
   * @return The reason at the given index.
   */
  public String getReason(int index) {
    return reason_.get(index);
  }
  /**
   * <code>repeated string reason = 3 [json_name = "reason"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the reason at the given index.
   */
  public com.google.protobuf.ByteString
      getReasonBytes(int index) {
    return reason_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pid_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, pid_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(code_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, code_);
    }
    for (int i = 0; i < reason_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, reason_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pid_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, pid_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(code_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, code_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < reason_.size(); i++) {
        dataSize += computeStringSizeNoTag(reason_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getReasonList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ContractTerminateRequest)) {
      return super.equals(obj);
    }
    ContractTerminateRequest other = (ContractTerminateRequest) obj;

    if (!getPid()
        .equals(other.getPid())) return false;
    if (!getCode()
        .equals(other.getCode())) return false;
    if (!getReasonList()
        .equals(other.getReasonList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PID_FIELD_NUMBER;
    hash = (53 * hash) + getPid().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode().hashCode();
    if (getReasonCount() > 0) {
      hash = (37 * hash) + REASON_FIELD_NUMBER;
      hash = (53 * hash) + getReasonList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ContractTerminateRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ContractTerminateRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ContractTerminateRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ContractTerminateRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ContractTerminateRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ContractTerminateRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ContractTerminateRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ContractTerminateRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ContractTerminateRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ContractTerminateRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ContractTerminateRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ContractTerminateRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ContractTerminateRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ContractTerminateRequest contains the pid, code, and reason of the contract negotiation to terminate.
   * </pre>
   *
   * Protobuf type {@code dsp.v1alpha2.ContractTerminateRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dsp.v1alpha2.ContractTerminateRequest)
      ContractTerminateRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ControlProto.internal_static_dsp_v1alpha2_ContractTerminateRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ControlProto.internal_static_dsp_v1alpha2_ContractTerminateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ContractTerminateRequest.class, Builder.class);
    }

    // Construct using com.dsp.v1alpha2.ContractTerminateRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      pid_ = "";
      code_ = "";
      reason_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ControlProto.internal_static_dsp_v1alpha2_ContractTerminateRequest_descriptor;
    }

    @Override
    public ContractTerminateRequest getDefaultInstanceForType() {
      return ContractTerminateRequest.getDefaultInstance();
    }

    @Override
    public ContractTerminateRequest build() {
      ContractTerminateRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ContractTerminateRequest buildPartial() {
      ContractTerminateRequest result = new ContractTerminateRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(ContractTerminateRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.pid_ = pid_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.code_ = code_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        reason_.makeImmutable();
        result.reason_ = reason_;
      }
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ContractTerminateRequest) {
        return mergeFrom((ContractTerminateRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ContractTerminateRequest other) {
      if (other == ContractTerminateRequest.getDefaultInstance()) return this;
      if (!other.getPid().isEmpty()) {
        pid_ = other.pid_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getCode().isEmpty()) {
        code_ = other.code_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.reason_.isEmpty()) {
        if (reason_.isEmpty()) {
          reason_ = other.reason_;
          bitField0_ |= 0x00000004;
        } else {
          ensureReasonIsMutable();
          reason_.addAll(other.reason_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              pid_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              code_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              String s = input.readStringRequireUtf8();
              ensureReasonIsMutable();
              reason_.add(s);
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object pid_ = "";
    /**
     * <code>string pid = 1 [json_name = "pid"];</code>
     * @return The pid.
     */
    public String getPid() {
      Object ref = pid_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        pid_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string pid = 1 [json_name = "pid"];</code>
     * @return The bytes for pid.
     */
    public com.google.protobuf.ByteString
        getPidBytes() {
      Object ref = pid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        pid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pid = 1 [json_name = "pid"];</code>
     * @param value The pid to set.
     * @return This builder for chaining.
     */
    public Builder setPid(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      pid_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string pid = 1 [json_name = "pid"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPid() {
      pid_ = getDefaultInstance().getPid();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string pid = 1 [json_name = "pid"];</code>
     * @param value The bytes for pid to set.
     * @return This builder for chaining.
     */
    public Builder setPidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      pid_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private Object code_ = "";
    /**
     * <code>string code = 2 [json_name = "code"];</code>
     * @return The code.
     */
    public String getCode() {
      Object ref = code_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        code_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string code = 2 [json_name = "code"];</code>
     * @return The bytes for code.
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      Object ref = code_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string code = 2 [json_name = "code"];</code>
     * @param value The code to set.
     * @return This builder for chaining.
     */
    public Builder setCode(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      code_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string code = 2 [json_name = "code"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCode() {
      code_ = getDefaultInstance().getCode();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string code = 2 [json_name = "code"];</code>
     * @param value The bytes for code to set.
     * @return This builder for chaining.
     */
    public Builder setCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      code_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList reason_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureReasonIsMutable() {
      if (!reason_.isModifiable()) {
        reason_ = new com.google.protobuf.LazyStringArrayList(reason_);
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <code>repeated string reason = 3 [json_name = "reason"];</code>
     * @return A list containing the reason.
     */
    public com.google.protobuf.ProtocolStringList
        getReasonList() {
      reason_.makeImmutable();
      return reason_;
    }
    /**
     * <code>repeated string reason = 3 [json_name = "reason"];</code>
     * @return The count of reason.
     */
    public int getReasonCount() {
      return reason_.size();
    }
    /**
     * <code>repeated string reason = 3 [json_name = "reason"];</code>
     * @param index The index of the element to return.
     * @return The reason at the given index.
     */
    public String getReason(int index) {
      return reason_.get(index);
    }
    /**
     * <code>repeated string reason = 3 [json_name = "reason"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the reason at the given index.
     */
    public com.google.protobuf.ByteString
        getReasonBytes(int index) {
      return reason_.getByteString(index);
    }
    /**
     * <code>repeated string reason = 3 [json_name = "reason"];</code>
     * @param index The index to set the value at.
     * @param value The reason to set.
     * @return This builder for chaining.
     */
    public Builder setReason(
        int index, String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureReasonIsMutable();
      reason_.set(index, value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string reason = 3 [json_name = "reason"];</code>
     * @param value The reason to add.
     * @return This builder for chaining.
     */
    public Builder addReason(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureReasonIsMutable();
      reason_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string reason = 3 [json_name = "reason"];</code>
     * @param values The reason to add.
     * @return This builder for chaining.
     */
    public Builder addAllReason(
        Iterable<String> values) {
      ensureReasonIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, reason_);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string reason = 3 [json_name = "reason"];</code>
     * @return This builder for chaining.
     */
    public Builder clearReason() {
      reason_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string reason = 3 [json_name = "reason"];</code>
     * @param value The bytes of the reason to add.
     * @return This builder for chaining.
     */
    public Builder addReasonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureReasonIsMutable();
      reason_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dsp.v1alpha2.ContractTerminateRequest)
  }

  // @@protoc_insertion_point(class_scope:dsp.v1alpha2.ContractTerminateRequest)
  private static final ContractTerminateRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ContractTerminateRequest();
  }

  public static ContractTerminateRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ContractTerminateRequest>
      PARSER = new com.google.protobuf.AbstractParser<ContractTerminateRequest>() {
    @Override
    public ContractTerminateRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ContractTerminateRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ContractTerminateRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public ContractTerminateRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

