// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dsp/v1alpha2/contract.proto

// Protobuf Java Version: 3.25.3
package com.dsp.v1alpha2;

/**
 * <pre>
 * ContractServiceConfigureRequest represents the configuration request RUN-DSP does to the contract service.
 * </pre>
 *
 * Protobuf type {@code dsp.v1alpha2.ContractServiceConfigureRequest}
 */
public final class ContractServiceConfigureRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dsp.v1alpha2.ContractServiceConfigureRequest)
    ContractServiceConfigureRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ContractServiceConfigureRequest.newBuilder() to construct.
  private ContractServiceConfigureRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ContractServiceConfigureRequest() {
    connectorAddress_ = "";
    verificationToken_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new ContractServiceConfigureRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ContractProto.internal_static_dsp_v1alpha2_ContractServiceConfigureRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ContractProto.internal_static_dsp_v1alpha2_ContractServiceConfigureRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ContractServiceConfigureRequest.class, Builder.class);
  }

  public static final int CONNECTOR_ADDRESS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile Object connectorAddress_ = "";
  /**
   * <pre>
   * The gRPC address RUN-DSP will listen to for control directives.
   * </pre>
   *
   * <code>string connector_address = 1 [json_name = "connectorAddress"];</code>
   * @return The connectorAddress.
   */
  @Override
  public String getConnectorAddress() {
    Object ref = connectorAddress_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      connectorAddress_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The gRPC address RUN-DSP will listen to for control directives.
   * </pre>
   *
   * <code>string connector_address = 1 [json_name = "connectorAddress"];</code>
   * @return The bytes for connectorAddress.
   */
  @Override
  public com.google.protobuf.ByteString
      getConnectorAddressBytes() {
    Object ref = connectorAddress_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      connectorAddress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERIFICATION_TOKEN_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile Object verificationToken_ = "";
  /**
   * <pre>
   * The verification token generated by RUN-DSP to use when we are verifying the above address.
   * </pre>
   *
   * <code>string verification_token = 2 [json_name = "verificationToken"];</code>
   * @return The verificationToken.
   */
  @Override
  public String getVerificationToken() {
    Object ref = verificationToken_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      verificationToken_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The verification token generated by RUN-DSP to use when we are verifying the above address.
   * </pre>
   *
   * <code>string verification_token = 2 [json_name = "verificationToken"];</code>
   * @return The bytes for verificationToken.
   */
  @Override
  public com.google.protobuf.ByteString
      getVerificationTokenBytes() {
    Object ref = verificationToken_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      verificationToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(connectorAddress_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, connectorAddress_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(verificationToken_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, verificationToken_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(connectorAddress_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, connectorAddress_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(verificationToken_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, verificationToken_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ContractServiceConfigureRequest)) {
      return super.equals(obj);
    }
    ContractServiceConfigureRequest other = (ContractServiceConfigureRequest) obj;

    if (!getConnectorAddress()
        .equals(other.getConnectorAddress())) return false;
    if (!getVerificationToken()
        .equals(other.getVerificationToken())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONNECTOR_ADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getConnectorAddress().hashCode();
    hash = (37 * hash) + VERIFICATION_TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getVerificationToken().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ContractServiceConfigureRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ContractServiceConfigureRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ContractServiceConfigureRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ContractServiceConfigureRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ContractServiceConfigureRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ContractServiceConfigureRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ContractServiceConfigureRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ContractServiceConfigureRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ContractServiceConfigureRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ContractServiceConfigureRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ContractServiceConfigureRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ContractServiceConfigureRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ContractServiceConfigureRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ContractServiceConfigureRequest represents the configuration request RUN-DSP does to the contract service.
   * </pre>
   *
   * Protobuf type {@code dsp.v1alpha2.ContractServiceConfigureRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dsp.v1alpha2.ContractServiceConfigureRequest)
      ContractServiceConfigureRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ContractProto.internal_static_dsp_v1alpha2_ContractServiceConfigureRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ContractProto.internal_static_dsp_v1alpha2_ContractServiceConfigureRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ContractServiceConfigureRequest.class, Builder.class);
    }

    // Construct using com.dsp.v1alpha2.ContractServiceConfigureRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      connectorAddress_ = "";
      verificationToken_ = "";
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ContractProto.internal_static_dsp_v1alpha2_ContractServiceConfigureRequest_descriptor;
    }

    @Override
    public ContractServiceConfigureRequest getDefaultInstanceForType() {
      return ContractServiceConfigureRequest.getDefaultInstance();
    }

    @Override
    public ContractServiceConfigureRequest build() {
      ContractServiceConfigureRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ContractServiceConfigureRequest buildPartial() {
      ContractServiceConfigureRequest result = new ContractServiceConfigureRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(ContractServiceConfigureRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.connectorAddress_ = connectorAddress_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.verificationToken_ = verificationToken_;
      }
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ContractServiceConfigureRequest) {
        return mergeFrom((ContractServiceConfigureRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ContractServiceConfigureRequest other) {
      if (other == ContractServiceConfigureRequest.getDefaultInstance()) return this;
      if (!other.getConnectorAddress().isEmpty()) {
        connectorAddress_ = other.connectorAddress_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getVerificationToken().isEmpty()) {
        verificationToken_ = other.verificationToken_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              connectorAddress_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              verificationToken_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object connectorAddress_ = "";
    /**
     * <pre>
     * The gRPC address RUN-DSP will listen to for control directives.
     * </pre>
     *
     * <code>string connector_address = 1 [json_name = "connectorAddress"];</code>
     * @return The connectorAddress.
     */
    public String getConnectorAddress() {
      Object ref = connectorAddress_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        connectorAddress_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * The gRPC address RUN-DSP will listen to for control directives.
     * </pre>
     *
     * <code>string connector_address = 1 [json_name = "connectorAddress"];</code>
     * @return The bytes for connectorAddress.
     */
    public com.google.protobuf.ByteString
        getConnectorAddressBytes() {
      Object ref = connectorAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        connectorAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The gRPC address RUN-DSP will listen to for control directives.
     * </pre>
     *
     * <code>string connector_address = 1 [json_name = "connectorAddress"];</code>
     * @param value The connectorAddress to set.
     * @return This builder for chaining.
     */
    public Builder setConnectorAddress(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      connectorAddress_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The gRPC address RUN-DSP will listen to for control directives.
     * </pre>
     *
     * <code>string connector_address = 1 [json_name = "connectorAddress"];</code>
     * @return This builder for chaining.
     */
    public Builder clearConnectorAddress() {
      connectorAddress_ = getDefaultInstance().getConnectorAddress();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The gRPC address RUN-DSP will listen to for control directives.
     * </pre>
     *
     * <code>string connector_address = 1 [json_name = "connectorAddress"];</code>
     * @param value The bytes for connectorAddress to set.
     * @return This builder for chaining.
     */
    public Builder setConnectorAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      connectorAddress_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private Object verificationToken_ = "";
    /**
     * <pre>
     * The verification token generated by RUN-DSP to use when we are verifying the above address.
     * </pre>
     *
     * <code>string verification_token = 2 [json_name = "verificationToken"];</code>
     * @return The verificationToken.
     */
    public String getVerificationToken() {
      Object ref = verificationToken_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        verificationToken_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * The verification token generated by RUN-DSP to use when we are verifying the above address.
     * </pre>
     *
     * <code>string verification_token = 2 [json_name = "verificationToken"];</code>
     * @return The bytes for verificationToken.
     */
    public com.google.protobuf.ByteString
        getVerificationTokenBytes() {
      Object ref = verificationToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        verificationToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The verification token generated by RUN-DSP to use when we are verifying the above address.
     * </pre>
     *
     * <code>string verification_token = 2 [json_name = "verificationToken"];</code>
     * @param value The verificationToken to set.
     * @return This builder for chaining.
     */
    public Builder setVerificationToken(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      verificationToken_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The verification token generated by RUN-DSP to use when we are verifying the above address.
     * </pre>
     *
     * <code>string verification_token = 2 [json_name = "verificationToken"];</code>
     * @return This builder for chaining.
     */
    public Builder clearVerificationToken() {
      verificationToken_ = getDefaultInstance().getVerificationToken();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The verification token generated by RUN-DSP to use when we are verifying the above address.
     * </pre>
     *
     * <code>string verification_token = 2 [json_name = "verificationToken"];</code>
     * @param value The bytes for verificationToken to set.
     * @return This builder for chaining.
     */
    public Builder setVerificationTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      verificationToken_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dsp.v1alpha2.ContractServiceConfigureRequest)
  }

  // @@protoc_insertion_point(class_scope:dsp.v1alpha2.ContractServiceConfigureRequest)
  private static final ContractServiceConfigureRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ContractServiceConfigureRequest();
  }

  public static ContractServiceConfigureRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ContractServiceConfigureRequest>
      PARSER = new com.google.protobuf.AbstractParser<ContractServiceConfigureRequest>() {
    @Override
    public ContractServiceConfigureRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ContractServiceConfigureRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ContractServiceConfigureRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public ContractServiceConfigureRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

