// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dsp/v1alpha2/contract.proto

// Protobuf Java Version: 3.25.3
package com.dsp.v1alpha2;

/**
 * <pre>
 * ContractServiceRequestReceivedRequest contains the pid RUN-DSP uses to refer to the negotiation and offer contains
 * the raw JSON of the offer ODRL.
 * </pre>
 *
 * Protobuf type {@code dsp.v1alpha2.ContractServiceRequestReceivedRequest}
 */
public final class ContractServiceRequestReceivedRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dsp.v1alpha2.ContractServiceRequestReceivedRequest)
    ContractServiceRequestReceivedRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ContractServiceRequestReceivedRequest.newBuilder() to construct.
  private ContractServiceRequestReceivedRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ContractServiceRequestReceivedRequest() {
    pid_ = "";
    offer_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new ContractServiceRequestReceivedRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ContractProto.internal_static_dsp_v1alpha2_ContractServiceRequestReceivedRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ContractProto.internal_static_dsp_v1alpha2_ContractServiceRequestReceivedRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ContractServiceRequestReceivedRequest.class, Builder.class);
  }

  public static final int PID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile Object pid_ = "";
  /**
   * <code>string pid = 1 [json_name = "pid"];</code>
   * @return The pid.
   */
  @Override
  public String getPid() {
    Object ref = pid_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      pid_ = s;
      return s;
    }
  }
  /**
   * <code>string pid = 1 [json_name = "pid"];</code>
   * @return The bytes for pid.
   */
  @Override
  public com.google.protobuf.ByteString
      getPidBytes() {
    Object ref = pid_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      pid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OFFER_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile Object offer_ = "";
  /**
   * <code>string offer = 2 [json_name = "offer"];</code>
   * @return The offer.
   */
  @Override
  public String getOffer() {
    Object ref = offer_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      offer_ = s;
      return s;
    }
  }
  /**
   * <code>string offer = 2 [json_name = "offer"];</code>
   * @return The bytes for offer.
   */
  @Override
  public com.google.protobuf.ByteString
      getOfferBytes() {
    Object ref = offer_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      offer_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pid_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, pid_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(offer_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, offer_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pid_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, pid_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(offer_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, offer_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ContractServiceRequestReceivedRequest)) {
      return super.equals(obj);
    }
    ContractServiceRequestReceivedRequest other = (ContractServiceRequestReceivedRequest) obj;

    if (!getPid()
        .equals(other.getPid())) return false;
    if (!getOffer()
        .equals(other.getOffer())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PID_FIELD_NUMBER;
    hash = (53 * hash) + getPid().hashCode();
    hash = (37 * hash) + OFFER_FIELD_NUMBER;
    hash = (53 * hash) + getOffer().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ContractServiceRequestReceivedRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ContractServiceRequestReceivedRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ContractServiceRequestReceivedRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ContractServiceRequestReceivedRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ContractServiceRequestReceivedRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ContractServiceRequestReceivedRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ContractServiceRequestReceivedRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ContractServiceRequestReceivedRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ContractServiceRequestReceivedRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ContractServiceRequestReceivedRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ContractServiceRequestReceivedRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ContractServiceRequestReceivedRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ContractServiceRequestReceivedRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ContractServiceRequestReceivedRequest contains the pid RUN-DSP uses to refer to the negotiation and offer contains
   * the raw JSON of the offer ODRL.
   * </pre>
   *
   * Protobuf type {@code dsp.v1alpha2.ContractServiceRequestReceivedRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dsp.v1alpha2.ContractServiceRequestReceivedRequest)
      ContractServiceRequestReceivedRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ContractProto.internal_static_dsp_v1alpha2_ContractServiceRequestReceivedRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ContractProto.internal_static_dsp_v1alpha2_ContractServiceRequestReceivedRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ContractServiceRequestReceivedRequest.class, Builder.class);
    }

    // Construct using com.dsp.v1alpha2.ContractServiceRequestReceivedRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      pid_ = "";
      offer_ = "";
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ContractProto.internal_static_dsp_v1alpha2_ContractServiceRequestReceivedRequest_descriptor;
    }

    @Override
    public ContractServiceRequestReceivedRequest getDefaultInstanceForType() {
      return ContractServiceRequestReceivedRequest.getDefaultInstance();
    }

    @Override
    public ContractServiceRequestReceivedRequest build() {
      ContractServiceRequestReceivedRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ContractServiceRequestReceivedRequest buildPartial() {
      ContractServiceRequestReceivedRequest result = new ContractServiceRequestReceivedRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(ContractServiceRequestReceivedRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.pid_ = pid_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.offer_ = offer_;
      }
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ContractServiceRequestReceivedRequest) {
        return mergeFrom((ContractServiceRequestReceivedRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ContractServiceRequestReceivedRequest other) {
      if (other == ContractServiceRequestReceivedRequest.getDefaultInstance()) return this;
      if (!other.getPid().isEmpty()) {
        pid_ = other.pid_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getOffer().isEmpty()) {
        offer_ = other.offer_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              pid_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              offer_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object pid_ = "";
    /**
     * <code>string pid = 1 [json_name = "pid"];</code>
     * @return The pid.
     */
    public String getPid() {
      Object ref = pid_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        pid_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string pid = 1 [json_name = "pid"];</code>
     * @return The bytes for pid.
     */
    public com.google.protobuf.ByteString
        getPidBytes() {
      Object ref = pid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        pid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pid = 1 [json_name = "pid"];</code>
     * @param value The pid to set.
     * @return This builder for chaining.
     */
    public Builder setPid(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      pid_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string pid = 1 [json_name = "pid"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPid() {
      pid_ = getDefaultInstance().getPid();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string pid = 1 [json_name = "pid"];</code>
     * @param value The bytes for pid to set.
     * @return This builder for chaining.
     */
    public Builder setPidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      pid_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private Object offer_ = "";
    /**
     * <code>string offer = 2 [json_name = "offer"];</code>
     * @return The offer.
     */
    public String getOffer() {
      Object ref = offer_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        offer_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string offer = 2 [json_name = "offer"];</code>
     * @return The bytes for offer.
     */
    public com.google.protobuf.ByteString
        getOfferBytes() {
      Object ref = offer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        offer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string offer = 2 [json_name = "offer"];</code>
     * @param value The offer to set.
     * @return This builder for chaining.
     */
    public Builder setOffer(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      offer_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string offer = 2 [json_name = "offer"];</code>
     * @return This builder for chaining.
     */
    public Builder clearOffer() {
      offer_ = getDefaultInstance().getOffer();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string offer = 2 [json_name = "offer"];</code>
     * @param value The bytes for offer to set.
     * @return This builder for chaining.
     */
    public Builder setOfferBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      offer_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dsp.v1alpha2.ContractServiceRequestReceivedRequest)
  }

  // @@protoc_insertion_point(class_scope:dsp.v1alpha2.ContractServiceRequestReceivedRequest)
  private static final ContractServiceRequestReceivedRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ContractServiceRequestReceivedRequest();
  }

  public static ContractServiceRequestReceivedRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ContractServiceRequestReceivedRequest>
      PARSER = new com.google.protobuf.AbstractParser<ContractServiceRequestReceivedRequest>() {
    @Override
    public ContractServiceRequestReceivedRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ContractServiceRequestReceivedRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ContractServiceRequestReceivedRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public ContractServiceRequestReceivedRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

