// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dsp/v1alpha2/provider.proto

// Protobuf Java Version: 3.25.3
package com.dsp.v1alpha2;

/**
 * <pre>
 * GetCatalogRequest represents the parameters for the GetCatalog call.
 * </pre>
 *
 * Protobuf type {@code dsp.v1alpha2.GetCatalogueRequest}
 */
public final class GetCatalogueRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dsp.v1alpha2.GetCatalogueRequest)
    GetCatalogueRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetCatalogueRequest.newBuilder() to construct.
  private GetCatalogueRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetCatalogueRequest() {
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetCatalogueRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ProviderProto.internal_static_dsp_v1alpha2_GetCatalogueRequest_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 1:
        return internalGetQueryParameters();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ProviderProto.internal_static_dsp_v1alpha2_GetCatalogueRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            GetCatalogueRequest.class, Builder.class);
  }

  public static final int QUERY_PARAMETERS_FIELD_NUMBER = 1;
  private static final class QueryParametersDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        String, String> defaultEntry =
            com.google.protobuf.MapEntry
            .<String, String>newDefaultInstance(
                ProviderProto.internal_static_dsp_v1alpha2_GetCatalogueRequest_QueryParametersEntry_descriptor,
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      String, String> queryParameters_;
  private com.google.protobuf.MapField<String, String>
  internalGetQueryParameters() {
    if (queryParameters_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          QueryParametersDefaultEntryHolder.defaultEntry);
    }
    return queryParameters_;
  }
  public int getQueryParametersCount() {
    return internalGetQueryParameters().getMap().size();
  }
  /**
   * <pre>
   * query_parameters is just a key/value map. These are not specified in the dataspace standard.
   * RUN-DSP also does not define them yet, so for now this is a placeholder.
   * </pre>
   *
   * <code>map&lt;string, string&gt; query_parameters = 1 [json_name = "queryParameters"];</code>
   */
  @Override
  public boolean containsQueryParameters(
      String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetQueryParameters().getMap().containsKey(key);
  }
  /**
   * Use {@link #getQueryParametersMap()} instead.
   */
  @Override
  @Deprecated
  public java.util.Map<String, String> getQueryParameters() {
    return getQueryParametersMap();
  }
  /**
   * <pre>
   * query_parameters is just a key/value map. These are not specified in the dataspace standard.
   * RUN-DSP also does not define them yet, so for now this is a placeholder.
   * </pre>
   *
   * <code>map&lt;string, string&gt; query_parameters = 1 [json_name = "queryParameters"];</code>
   */
  @Override
  public java.util.Map<String, String> getQueryParametersMap() {
    return internalGetQueryParameters().getMap();
  }
  /**
   * <pre>
   * query_parameters is just a key/value map. These are not specified in the dataspace standard.
   * RUN-DSP also does not define them yet, so for now this is a placeholder.
   * </pre>
   *
   * <code>map&lt;string, string&gt; query_parameters = 1 [json_name = "queryParameters"];</code>
   */
  @Override
  public /* nullable */
String getQueryParametersOrDefault(
      String key,
      /* nullable */
String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<String, String> map =
        internalGetQueryParameters().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * query_parameters is just a key/value map. These are not specified in the dataspace standard.
   * RUN-DSP also does not define them yet, so for now this is a placeholder.
   * </pre>
   *
   * <code>map&lt;string, string&gt; query_parameters = 1 [json_name = "queryParameters"];</code>
   */
  @Override
  public String getQueryParametersOrThrow(
      String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<String, String> map =
        internalGetQueryParameters().getMap();
    if (!map.containsKey(key)) {
      throw new IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetQueryParameters(),
        QueryParametersDefaultEntryHolder.defaultEntry,
        1);
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<String, String> entry
         : internalGetQueryParameters().getMap().entrySet()) {
      com.google.protobuf.MapEntry<String, String>
      queryParameters__ = QueryParametersDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, queryParameters__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof GetCatalogueRequest)) {
      return super.equals(obj);
    }
    GetCatalogueRequest other = (GetCatalogueRequest) obj;

    if (!internalGetQueryParameters().equals(
        other.internalGetQueryParameters())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetQueryParameters().getMap().isEmpty()) {
      hash = (37 * hash) + QUERY_PARAMETERS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetQueryParameters().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static GetCatalogueRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetCatalogueRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetCatalogueRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetCatalogueRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetCatalogueRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetCatalogueRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetCatalogueRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static GetCatalogueRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static GetCatalogueRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static GetCatalogueRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static GetCatalogueRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static GetCatalogueRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(GetCatalogueRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * GetCatalogRequest represents the parameters for the GetCatalog call.
   * </pre>
   *
   * Protobuf type {@code dsp.v1alpha2.GetCatalogueRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dsp.v1alpha2.GetCatalogueRequest)
      GetCatalogueRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProviderProto.internal_static_dsp_v1alpha2_GetCatalogueRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetQueryParameters();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableQueryParameters();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProviderProto.internal_static_dsp_v1alpha2_GetCatalogueRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GetCatalogueRequest.class, Builder.class);
    }

    // Construct using com.dsp.v1alpha2.GetCatalogueRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      internalGetMutableQueryParameters().clear();
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ProviderProto.internal_static_dsp_v1alpha2_GetCatalogueRequest_descriptor;
    }

    @Override
    public GetCatalogueRequest getDefaultInstanceForType() {
      return GetCatalogueRequest.getDefaultInstance();
    }

    @Override
    public GetCatalogueRequest build() {
      GetCatalogueRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public GetCatalogueRequest buildPartial() {
      GetCatalogueRequest result = new GetCatalogueRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(GetCatalogueRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.queryParameters_ = internalGetQueryParameters();
        result.queryParameters_.makeImmutable();
      }
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof GetCatalogueRequest) {
        return mergeFrom((GetCatalogueRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(GetCatalogueRequest other) {
      if (other == GetCatalogueRequest.getDefaultInstance()) return this;
      internalGetMutableQueryParameters().mergeFrom(
          other.internalGetQueryParameters());
      bitField0_ |= 0x00000001;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.MapEntry<String, String>
              queryParameters__ = input.readMessage(
                  QueryParametersDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableQueryParameters().getMutableMap().put(
                  queryParameters__.getKey(), queryParameters__.getValue());
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        String, String> queryParameters_;
    private com.google.protobuf.MapField<String, String>
        internalGetQueryParameters() {
      if (queryParameters_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            QueryParametersDefaultEntryHolder.defaultEntry);
      }
      return queryParameters_;
    }
    private com.google.protobuf.MapField<String, String>
        internalGetMutableQueryParameters() {
      if (queryParameters_ == null) {
        queryParameters_ = com.google.protobuf.MapField.newMapField(
            QueryParametersDefaultEntryHolder.defaultEntry);
      }
      if (!queryParameters_.isMutable()) {
        queryParameters_ = queryParameters_.copy();
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return queryParameters_;
    }
    public int getQueryParametersCount() {
      return internalGetQueryParameters().getMap().size();
    }
    /**
     * <pre>
     * query_parameters is just a key/value map. These are not specified in the dataspace standard.
     * RUN-DSP also does not define them yet, so for now this is a placeholder.
     * </pre>
     *
     * <code>map&lt;string, string&gt; query_parameters = 1 [json_name = "queryParameters"];</code>
     */
    @Override
    public boolean containsQueryParameters(
        String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetQueryParameters().getMap().containsKey(key);
    }
    /**
     * Use {@link #getQueryParametersMap()} instead.
     */
    @Override
    @Deprecated
    public java.util.Map<String, String> getQueryParameters() {
      return getQueryParametersMap();
    }
    /**
     * <pre>
     * query_parameters is just a key/value map. These are not specified in the dataspace standard.
     * RUN-DSP also does not define them yet, so for now this is a placeholder.
     * </pre>
     *
     * <code>map&lt;string, string&gt; query_parameters = 1 [json_name = "queryParameters"];</code>
     */
    @Override
    public java.util.Map<String, String> getQueryParametersMap() {
      return internalGetQueryParameters().getMap();
    }
    /**
     * <pre>
     * query_parameters is just a key/value map. These are not specified in the dataspace standard.
     * RUN-DSP also does not define them yet, so for now this is a placeholder.
     * </pre>
     *
     * <code>map&lt;string, string&gt; query_parameters = 1 [json_name = "queryParameters"];</code>
     */
    @Override
    public /* nullable */
String getQueryParametersOrDefault(
        String key,
        /* nullable */
String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<String, String> map =
          internalGetQueryParameters().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * query_parameters is just a key/value map. These are not specified in the dataspace standard.
     * RUN-DSP also does not define them yet, so for now this is a placeholder.
     * </pre>
     *
     * <code>map&lt;string, string&gt; query_parameters = 1 [json_name = "queryParameters"];</code>
     */
    @Override
    public String getQueryParametersOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<String, String> map =
          internalGetQueryParameters().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearQueryParameters() {
      bitField0_ = (bitField0_ & ~0x00000001);
      internalGetMutableQueryParameters().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * query_parameters is just a key/value map. These are not specified in the dataspace standard.
     * RUN-DSP also does not define them yet, so for now this is a placeholder.
     * </pre>
     *
     * <code>map&lt;string, string&gt; query_parameters = 1 [json_name = "queryParameters"];</code>
     */
    public Builder removeQueryParameters(
        String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableQueryParameters().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @Deprecated
    public java.util.Map<String, String>
        getMutableQueryParameters() {
      bitField0_ |= 0x00000001;
      return internalGetMutableQueryParameters().getMutableMap();
    }
    /**
     * <pre>
     * query_parameters is just a key/value map. These are not specified in the dataspace standard.
     * RUN-DSP also does not define them yet, so for now this is a placeholder.
     * </pre>
     *
     * <code>map&lt;string, string&gt; query_parameters = 1 [json_name = "queryParameters"];</code>
     */
    public Builder putQueryParameters(
        String key,
        String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableQueryParameters().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * query_parameters is just a key/value map. These are not specified in the dataspace standard.
     * RUN-DSP also does not define them yet, so for now this is a placeholder.
     * </pre>
     *
     * <code>map&lt;string, string&gt; query_parameters = 1 [json_name = "queryParameters"];</code>
     */
    public Builder putAllQueryParameters(
        java.util.Map<String, String> values) {
      internalGetMutableQueryParameters().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000001;
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dsp.v1alpha2.GetCatalogueRequest)
  }

  // @@protoc_insertion_point(class_scope:dsp.v1alpha2.GetCatalogueRequest)
  private static final GetCatalogueRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new GetCatalogueRequest();
  }

  public static GetCatalogueRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetCatalogueRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetCatalogueRequest>() {
    @Override
    public GetCatalogueRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetCatalogueRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<GetCatalogueRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public GetCatalogueRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

