// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dsp/v1alpha2/control.proto

// Protobuf Java Version: 3.25.3
package com.dsp.v1alpha2;

/**
 * <pre>
 * GetProviderDatasetResponse contains the requested dataset.
 * </pre>
 *
 * Protobuf type {@code dsp.v1alpha2.GetProviderDatasetResponse}
 */
public final class GetProviderDatasetResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dsp.v1alpha2.GetProviderDatasetResponse)
    GetProviderDatasetResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetProviderDatasetResponse.newBuilder() to construct.
  private GetProviderDatasetResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetProviderDatasetResponse() {
    providerUrl_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetProviderDatasetResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ControlProto.internal_static_dsp_v1alpha2_GetProviderDatasetResponse_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ControlProto.internal_static_dsp_v1alpha2_GetProviderDatasetResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            GetProviderDatasetResponse.class, Builder.class);
  }

  private int bitField0_;
  public static final int PROVIDER_URL_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile Object providerUrl_ = "";
  /**
   * <code>string provider_url = 1 [json_name = "providerUrl"];</code>
   * @return The providerUrl.
   */
  @Override
  public String getProviderUrl() {
    Object ref = providerUrl_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      providerUrl_ = s;
      return s;
    }
  }
  /**
   * <code>string provider_url = 1 [json_name = "providerUrl"];</code>
   * @return The bytes for providerUrl.
   */
  @Override
  public com.google.protobuf.ByteString
      getProviderUrlBytes() {
    Object ref = providerUrl_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      providerUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATASET_FIELD_NUMBER = 2;
  private Dataset dataset_;
  /**
   * <code>.dsp.v1alpha2.Dataset dataset = 2 [json_name = "dataset"];</code>
   * @return Whether the dataset field is set.
   */
  @Override
  public boolean hasDataset() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.dsp.v1alpha2.Dataset dataset = 2 [json_name = "dataset"];</code>
   * @return The dataset.
   */
  @Override
  public Dataset getDataset() {
    return dataset_ == null ? Dataset.getDefaultInstance() : dataset_;
  }
  /**
   * <code>.dsp.v1alpha2.Dataset dataset = 2 [json_name = "dataset"];</code>
   */
  @Override
  public DatasetOrBuilder getDatasetOrBuilder() {
    return dataset_ == null ? Dataset.getDefaultInstance() : dataset_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(providerUrl_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, providerUrl_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getDataset());
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(providerUrl_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, providerUrl_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getDataset());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof GetProviderDatasetResponse)) {
      return super.equals(obj);
    }
    GetProviderDatasetResponse other = (GetProviderDatasetResponse) obj;

    if (!getProviderUrl()
        .equals(other.getProviderUrl())) return false;
    if (hasDataset() != other.hasDataset()) return false;
    if (hasDataset()) {
      if (!getDataset()
          .equals(other.getDataset())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PROVIDER_URL_FIELD_NUMBER;
    hash = (53 * hash) + getProviderUrl().hashCode();
    if (hasDataset()) {
      hash = (37 * hash) + DATASET_FIELD_NUMBER;
      hash = (53 * hash) + getDataset().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static GetProviderDatasetResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetProviderDatasetResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetProviderDatasetResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetProviderDatasetResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetProviderDatasetResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetProviderDatasetResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetProviderDatasetResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static GetProviderDatasetResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static GetProviderDatasetResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static GetProviderDatasetResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static GetProviderDatasetResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static GetProviderDatasetResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(GetProviderDatasetResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * GetProviderDatasetResponse contains the requested dataset.
   * </pre>
   *
   * Protobuf type {@code dsp.v1alpha2.GetProviderDatasetResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dsp.v1alpha2.GetProviderDatasetResponse)
      GetProviderDatasetResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ControlProto.internal_static_dsp_v1alpha2_GetProviderDatasetResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ControlProto.internal_static_dsp_v1alpha2_GetProviderDatasetResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GetProviderDatasetResponse.class, Builder.class);
    }

    // Construct using com.dsp.v1alpha2.GetProviderDatasetResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDatasetFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      providerUrl_ = "";
      dataset_ = null;
      if (datasetBuilder_ != null) {
        datasetBuilder_.dispose();
        datasetBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ControlProto.internal_static_dsp_v1alpha2_GetProviderDatasetResponse_descriptor;
    }

    @Override
    public GetProviderDatasetResponse getDefaultInstanceForType() {
      return GetProviderDatasetResponse.getDefaultInstance();
    }

    @Override
    public GetProviderDatasetResponse build() {
      GetProviderDatasetResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public GetProviderDatasetResponse buildPartial() {
      GetProviderDatasetResponse result = new GetProviderDatasetResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(GetProviderDatasetResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.providerUrl_ = providerUrl_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.dataset_ = datasetBuilder_ == null
            ? dataset_
            : datasetBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof GetProviderDatasetResponse) {
        return mergeFrom((GetProviderDatasetResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(GetProviderDatasetResponse other) {
      if (other == GetProviderDatasetResponse.getDefaultInstance()) return this;
      if (!other.getProviderUrl().isEmpty()) {
        providerUrl_ = other.providerUrl_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasDataset()) {
        mergeDataset(other.getDataset());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              providerUrl_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getDatasetFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object providerUrl_ = "";
    /**
     * <code>string provider_url = 1 [json_name = "providerUrl"];</code>
     * @return The providerUrl.
     */
    public String getProviderUrl() {
      Object ref = providerUrl_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        providerUrl_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string provider_url = 1 [json_name = "providerUrl"];</code>
     * @return The bytes for providerUrl.
     */
    public com.google.protobuf.ByteString
        getProviderUrlBytes() {
      Object ref = providerUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        providerUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string provider_url = 1 [json_name = "providerUrl"];</code>
     * @param value The providerUrl to set.
     * @return This builder for chaining.
     */
    public Builder setProviderUrl(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      providerUrl_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string provider_url = 1 [json_name = "providerUrl"];</code>
     * @return This builder for chaining.
     */
    public Builder clearProviderUrl() {
      providerUrl_ = getDefaultInstance().getProviderUrl();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string provider_url = 1 [json_name = "providerUrl"];</code>
     * @param value The bytes for providerUrl to set.
     * @return This builder for chaining.
     */
    public Builder setProviderUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      providerUrl_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private Dataset dataset_;
    private com.google.protobuf.SingleFieldBuilderV3<
        Dataset, Dataset.Builder, DatasetOrBuilder> datasetBuilder_;
    /**
     * <code>.dsp.v1alpha2.Dataset dataset = 2 [json_name = "dataset"];</code>
     * @return Whether the dataset field is set.
     */
    public boolean hasDataset() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.dsp.v1alpha2.Dataset dataset = 2 [json_name = "dataset"];</code>
     * @return The dataset.
     */
    public Dataset getDataset() {
      if (datasetBuilder_ == null) {
        return dataset_ == null ? Dataset.getDefaultInstance() : dataset_;
      } else {
        return datasetBuilder_.getMessage();
      }
    }
    /**
     * <code>.dsp.v1alpha2.Dataset dataset = 2 [json_name = "dataset"];</code>
     */
    public Builder setDataset(Dataset value) {
      if (datasetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dataset_ = value;
      } else {
        datasetBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.dsp.v1alpha2.Dataset dataset = 2 [json_name = "dataset"];</code>
     */
    public Builder setDataset(
        Dataset.Builder builderForValue) {
      if (datasetBuilder_ == null) {
        dataset_ = builderForValue.build();
      } else {
        datasetBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.dsp.v1alpha2.Dataset dataset = 2 [json_name = "dataset"];</code>
     */
    public Builder mergeDataset(Dataset value) {
      if (datasetBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          dataset_ != null &&
          dataset_ != Dataset.getDefaultInstance()) {
          getDatasetBuilder().mergeFrom(value);
        } else {
          dataset_ = value;
        }
      } else {
        datasetBuilder_.mergeFrom(value);
      }
      if (dataset_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.dsp.v1alpha2.Dataset dataset = 2 [json_name = "dataset"];</code>
     */
    public Builder clearDataset() {
      bitField0_ = (bitField0_ & ~0x00000002);
      dataset_ = null;
      if (datasetBuilder_ != null) {
        datasetBuilder_.dispose();
        datasetBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.dsp.v1alpha2.Dataset dataset = 2 [json_name = "dataset"];</code>
     */
    public Dataset.Builder getDatasetBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getDatasetFieldBuilder().getBuilder();
    }
    /**
     * <code>.dsp.v1alpha2.Dataset dataset = 2 [json_name = "dataset"];</code>
     */
    public DatasetOrBuilder getDatasetOrBuilder() {
      if (datasetBuilder_ != null) {
        return datasetBuilder_.getMessageOrBuilder();
      } else {
        return dataset_ == null ?
            Dataset.getDefaultInstance() : dataset_;
      }
    }
    /**
     * <code>.dsp.v1alpha2.Dataset dataset = 2 [json_name = "dataset"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Dataset, Dataset.Builder, DatasetOrBuilder>
        getDatasetFieldBuilder() {
      if (datasetBuilder_ == null) {
        datasetBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Dataset, Dataset.Builder, DatasetOrBuilder>(
                getDataset(),
                getParentForChildren(),
                isClean());
        dataset_ = null;
      }
      return datasetBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dsp.v1alpha2.GetProviderDatasetResponse)
  }

  // @@protoc_insertion_point(class_scope:dsp.v1alpha2.GetProviderDatasetResponse)
  private static final GetProviderDatasetResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new GetProviderDatasetResponse();
  }

  public static GetProviderDatasetResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetProviderDatasetResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetProviderDatasetResponse>() {
    @Override
    public GetProviderDatasetResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetProviderDatasetResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<GetProviderDatasetResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public GetProviderDatasetResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

