// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dsp/v1alpha2/provider.proto

// Protobuf Java Version: 3.25.3
package com.dsp.v1alpha2;

/**
 * <pre>
 * PingResponse contains infomational data about the provider.
 * </pre>
 *
 * Protobuf type {@code dsp.v1alpha2.PingResponse}
 */
public final class PingResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dsp.v1alpha2.PingResponse)
    PingResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PingResponse.newBuilder() to construct.
  private PingResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PingResponse() {
    providerName_ = "";
    providerDescription_ = "";
    dataserviceId_ = "";
    dataserviceUrl_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new PingResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ProviderProto.internal_static_dsp_v1alpha2_PingResponse_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ProviderProto.internal_static_dsp_v1alpha2_PingResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            PingResponse.class, Builder.class);
  }

  public static final int PROVIDER_NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile Object providerName_ = "";
  /**
   * <code>string provider_name = 1 [json_name = "providerName"];</code>
   * @return The providerName.
   */
  @Override
  public String getProviderName() {
    Object ref = providerName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      providerName_ = s;
      return s;
    }
  }
  /**
   * <code>string provider_name = 1 [json_name = "providerName"];</code>
   * @return The bytes for providerName.
   */
  @Override
  public com.google.protobuf.ByteString
      getProviderNameBytes() {
    Object ref = providerName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      providerName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROVIDER_DESCRIPTION_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile Object providerDescription_ = "";
  /**
   * <code>string provider_description = 2 [json_name = "providerDescription"];</code>
   * @return The providerDescription.
   */
  @Override
  public String getProviderDescription() {
    Object ref = providerDescription_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      providerDescription_ = s;
      return s;
    }
  }
  /**
   * <code>string provider_description = 2 [json_name = "providerDescription"];</code>
   * @return The bytes for providerDescription.
   */
  @Override
  public com.google.protobuf.ByteString
      getProviderDescriptionBytes() {
    Object ref = providerDescription_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      providerDescription_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AUTHENTICATED_FIELD_NUMBER = 3;
  private boolean authenticated_ = false;
  /**
   * <code>bool authenticated = 3 [json_name = "authenticated"];</code>
   * @return The authenticated.
   */
  @Override
  public boolean getAuthenticated() {
    return authenticated_;
  }

  public static final int DATASERVICE_ID_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile Object dataserviceId_ = "";
  /**
   * <pre>
   * An ID for the data service, can be any uuid as long as it's consistent.
   * </pre>
   *
   * <code>string dataservice_id = 4 [json_name = "dataserviceId"];</code>
   * @return The dataserviceId.
   */
  @Override
  public String getDataserviceId() {
    Object ref = dataserviceId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      dataserviceId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * An ID for the data service, can be any uuid as long as it's consistent.
   * </pre>
   *
   * <code>string dataservice_id = 4 [json_name = "dataserviceId"];</code>
   * @return The bytes for dataserviceId.
   */
  @Override
  public com.google.protobuf.ByteString
      getDataserviceIdBytes() {
    Object ref = dataserviceId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      dataserviceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATASERVICE_URL_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile Object dataserviceUrl_ = "";
  /**
   * <pre>
   * dataservice URL where data is downloaded from.
   * </pre>
   *
   * <code>string dataservice_url = 5 [json_name = "dataserviceUrl"];</code>
   * @return The dataserviceUrl.
   */
  @Override
  public String getDataserviceUrl() {
    Object ref = dataserviceUrl_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      dataserviceUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * dataservice URL where data is downloaded from.
   * </pre>
   *
   * <code>string dataservice_url = 5 [json_name = "dataserviceUrl"];</code>
   * @return The bytes for dataserviceUrl.
   */
  @Override
  public com.google.protobuf.ByteString
      getDataserviceUrlBytes() {
    Object ref = dataserviceUrl_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      dataserviceUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(providerName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, providerName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(providerDescription_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, providerDescription_);
    }
    if (authenticated_ != false) {
      output.writeBool(3, authenticated_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dataserviceId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, dataserviceId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dataserviceUrl_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, dataserviceUrl_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(providerName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, providerName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(providerDescription_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, providerDescription_);
    }
    if (authenticated_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, authenticated_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dataserviceId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, dataserviceId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dataserviceUrl_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, dataserviceUrl_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof PingResponse)) {
      return super.equals(obj);
    }
    PingResponse other = (PingResponse) obj;

    if (!getProviderName()
        .equals(other.getProviderName())) return false;
    if (!getProviderDescription()
        .equals(other.getProviderDescription())) return false;
    if (getAuthenticated()
        != other.getAuthenticated()) return false;
    if (!getDataserviceId()
        .equals(other.getDataserviceId())) return false;
    if (!getDataserviceUrl()
        .equals(other.getDataserviceUrl())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PROVIDER_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getProviderName().hashCode();
    hash = (37 * hash) + PROVIDER_DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getProviderDescription().hashCode();
    hash = (37 * hash) + AUTHENTICATED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAuthenticated());
    hash = (37 * hash) + DATASERVICE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getDataserviceId().hashCode();
    hash = (37 * hash) + DATASERVICE_URL_FIELD_NUMBER;
    hash = (53 * hash) + getDataserviceUrl().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static PingResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PingResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PingResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PingResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PingResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PingResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PingResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static PingResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static PingResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static PingResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static PingResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static PingResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(PingResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * PingResponse contains infomational data about the provider.
   * </pre>
   *
   * Protobuf type {@code dsp.v1alpha2.PingResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dsp.v1alpha2.PingResponse)
      PingResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProviderProto.internal_static_dsp_v1alpha2_PingResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProviderProto.internal_static_dsp_v1alpha2_PingResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PingResponse.class, Builder.class);
    }

    // Construct using com.dsp.v1alpha2.PingResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      providerName_ = "";
      providerDescription_ = "";
      authenticated_ = false;
      dataserviceId_ = "";
      dataserviceUrl_ = "";
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ProviderProto.internal_static_dsp_v1alpha2_PingResponse_descriptor;
    }

    @Override
    public PingResponse getDefaultInstanceForType() {
      return PingResponse.getDefaultInstance();
    }

    @Override
    public PingResponse build() {
      PingResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public PingResponse buildPartial() {
      PingResponse result = new PingResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(PingResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.providerName_ = providerName_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.providerDescription_ = providerDescription_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.authenticated_ = authenticated_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.dataserviceId_ = dataserviceId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.dataserviceUrl_ = dataserviceUrl_;
      }
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof PingResponse) {
        return mergeFrom((PingResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(PingResponse other) {
      if (other == PingResponse.getDefaultInstance()) return this;
      if (!other.getProviderName().isEmpty()) {
        providerName_ = other.providerName_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getProviderDescription().isEmpty()) {
        providerDescription_ = other.providerDescription_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getAuthenticated() != false) {
        setAuthenticated(other.getAuthenticated());
      }
      if (!other.getDataserviceId().isEmpty()) {
        dataserviceId_ = other.dataserviceId_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getDataserviceUrl().isEmpty()) {
        dataserviceUrl_ = other.dataserviceUrl_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              providerName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              providerDescription_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              authenticated_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              dataserviceId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              dataserviceUrl_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object providerName_ = "";
    /**
     * <code>string provider_name = 1 [json_name = "providerName"];</code>
     * @return The providerName.
     */
    public String getProviderName() {
      Object ref = providerName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        providerName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string provider_name = 1 [json_name = "providerName"];</code>
     * @return The bytes for providerName.
     */
    public com.google.protobuf.ByteString
        getProviderNameBytes() {
      Object ref = providerName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        providerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string provider_name = 1 [json_name = "providerName"];</code>
     * @param value The providerName to set.
     * @return This builder for chaining.
     */
    public Builder setProviderName(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      providerName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string provider_name = 1 [json_name = "providerName"];</code>
     * @return This builder for chaining.
     */
    public Builder clearProviderName() {
      providerName_ = getDefaultInstance().getProviderName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string provider_name = 1 [json_name = "providerName"];</code>
     * @param value The bytes for providerName to set.
     * @return This builder for chaining.
     */
    public Builder setProviderNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      providerName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private Object providerDescription_ = "";
    /**
     * <code>string provider_description = 2 [json_name = "providerDescription"];</code>
     * @return The providerDescription.
     */
    public String getProviderDescription() {
      Object ref = providerDescription_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        providerDescription_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string provider_description = 2 [json_name = "providerDescription"];</code>
     * @return The bytes for providerDescription.
     */
    public com.google.protobuf.ByteString
        getProviderDescriptionBytes() {
      Object ref = providerDescription_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        providerDescription_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string provider_description = 2 [json_name = "providerDescription"];</code>
     * @param value The providerDescription to set.
     * @return This builder for chaining.
     */
    public Builder setProviderDescription(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      providerDescription_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string provider_description = 2 [json_name = "providerDescription"];</code>
     * @return This builder for chaining.
     */
    public Builder clearProviderDescription() {
      providerDescription_ = getDefaultInstance().getProviderDescription();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string provider_description = 2 [json_name = "providerDescription"];</code>
     * @param value The bytes for providerDescription to set.
     * @return This builder for chaining.
     */
    public Builder setProviderDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      providerDescription_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private boolean authenticated_ ;
    /**
     * <code>bool authenticated = 3 [json_name = "authenticated"];</code>
     * @return The authenticated.
     */
    @Override
    public boolean getAuthenticated() {
      return authenticated_;
    }
    /**
     * <code>bool authenticated = 3 [json_name = "authenticated"];</code>
     * @param value The authenticated to set.
     * @return This builder for chaining.
     */
    public Builder setAuthenticated(boolean value) {

      authenticated_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>bool authenticated = 3 [json_name = "authenticated"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAuthenticated() {
      bitField0_ = (bitField0_ & ~0x00000004);
      authenticated_ = false;
      onChanged();
      return this;
    }

    private Object dataserviceId_ = "";
    /**
     * <pre>
     * An ID for the data service, can be any uuid as long as it's consistent.
     * </pre>
     *
     * <code>string dataservice_id = 4 [json_name = "dataserviceId"];</code>
     * @return The dataserviceId.
     */
    public String getDataserviceId() {
      Object ref = dataserviceId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        dataserviceId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * An ID for the data service, can be any uuid as long as it's consistent.
     * </pre>
     *
     * <code>string dataservice_id = 4 [json_name = "dataserviceId"];</code>
     * @return The bytes for dataserviceId.
     */
    public com.google.protobuf.ByteString
        getDataserviceIdBytes() {
      Object ref = dataserviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        dataserviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * An ID for the data service, can be any uuid as long as it's consistent.
     * </pre>
     *
     * <code>string dataservice_id = 4 [json_name = "dataserviceId"];</code>
     * @param value The dataserviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDataserviceId(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      dataserviceId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * An ID for the data service, can be any uuid as long as it's consistent.
     * </pre>
     *
     * <code>string dataservice_id = 4 [json_name = "dataserviceId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDataserviceId() {
      dataserviceId_ = getDefaultInstance().getDataserviceId();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * An ID for the data service, can be any uuid as long as it's consistent.
     * </pre>
     *
     * <code>string dataservice_id = 4 [json_name = "dataserviceId"];</code>
     * @param value The bytes for dataserviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDataserviceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      dataserviceId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private Object dataserviceUrl_ = "";
    /**
     * <pre>
     * dataservice URL where data is downloaded from.
     * </pre>
     *
     * <code>string dataservice_url = 5 [json_name = "dataserviceUrl"];</code>
     * @return The dataserviceUrl.
     */
    public String getDataserviceUrl() {
      Object ref = dataserviceUrl_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        dataserviceUrl_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * dataservice URL where data is downloaded from.
     * </pre>
     *
     * <code>string dataservice_url = 5 [json_name = "dataserviceUrl"];</code>
     * @return The bytes for dataserviceUrl.
     */
    public com.google.protobuf.ByteString
        getDataserviceUrlBytes() {
      Object ref = dataserviceUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        dataserviceUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * dataservice URL where data is downloaded from.
     * </pre>
     *
     * <code>string dataservice_url = 5 [json_name = "dataserviceUrl"];</code>
     * @param value The dataserviceUrl to set.
     * @return This builder for chaining.
     */
    public Builder setDataserviceUrl(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      dataserviceUrl_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * dataservice URL where data is downloaded from.
     * </pre>
     *
     * <code>string dataservice_url = 5 [json_name = "dataserviceUrl"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDataserviceUrl() {
      dataserviceUrl_ = getDefaultInstance().getDataserviceUrl();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * dataservice URL where data is downloaded from.
     * </pre>
     *
     * <code>string dataservice_url = 5 [json_name = "dataserviceUrl"];</code>
     * @param value The bytes for dataserviceUrl to set.
     * @return This builder for chaining.
     */
    public Builder setDataserviceUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      dataserviceUrl_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dsp.v1alpha2.PingResponse)
  }

  // @@protoc_insertion_point(class_scope:dsp.v1alpha2.PingResponse)
  private static final PingResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new PingResponse();
  }

  public static PingResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PingResponse>
      PARSER = new com.google.protobuf.AbstractParser<PingResponse>() {
    @Override
    public PingResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PingResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<PingResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public PingResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

