apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: $SECRETS_NAMESPACE
type: Opaque
data:
  mysql-password: $MYSQL_PW_BASE64

---

apiVersion: v1
kind: Secret
metadata:
  name: swc-encryption
  namespace: $SECRETS_NAMESPACE
type: Opaque
data:
  aes-key: $AESKEY_BASE64

---

apiVersion: v1
kind: Secret
metadata:
  name: swc-garmin-api-credentials
  namespace: $SECRETS_NAMESPACE
type: Opaque
data:
  consumer-key: $GARMIN_APIKEY_BASE64
  consumer-secret: $GARMIN_APIPW_BASE64

---

apiVersion: v1
kind: Secret
metadata:
  name: swc-edc-api
  namespace: $SECRETS_NAMESPACE
type: Opaque
data:
  api-key: $EDC_APIKEY_BASE64

---

apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-credentials
  namespace: $SECRETS_NAMESPACE
type: Opaque
data:
  username: $KEYCLOAK_ADMIN_USER_BASE64
  password: $KEYCLOAK_ADMIN_PW_BASE64
  client-secret: $KEYCLOAK_ADMIN_CLIENT_SECRET_BASE64

---

apiVersion: v1
kind: Secret
metadata:
  name: smartwearables-container-registry
  namespace: $SECRETS_NAMESPACE
type: kubernetes.io/dockerconfigjson
data: 
  .dockerconfigjson: $Docker_Config
  
---

apiVersion: v1
kind: Secret
metadata:
  name: connector-keystore
  namespace: $SECRETS_NAMESPACE
type: Opaque
data:
  keystore.p12: $KEYSTORE_TOKEN_BASE64
  keystore-password: $KEYSTORE_PW_BASE64
    
---

apiVersion: v1
kind: Secret
metadata:
  name: swc-vc-sign-key
  namespace: $SECRETS_NAMESPACE
type: Opaque
data:
  private.key: $SWC_VC_PRIVKEY_BASE64
  public.key: $SWC_VC_PUBKEY_BASE64
    
---

apiVersion: v1
kind: Secret
metadata:
  name: jwe-auth-private-key-file
  namespace: $SECRETS_NAMESPACE
type: Opaque
data:
  private.key: $JWE_PRIVKEY_BASE64
    
---

apiVersion: v1
kind: Secret
metadata:
  name: thryve-credentials
  namespace: $SECRETS_NAMESPACE
type: Opaque
data:
  username: $THRYVE_UNAME_BASE64
  password: $THRYVE_PW_BASE64
  app-id: $THRYVE_APPID_BASE64
  app-secret: $THRYVE_APPSEC_BASE64
  auth-redirect-uri: $THRYVE_REDIRECT_URI_BASE64
  
---

apiVersion: v1
kind: Secret
metadata:
  name: issuer-account-key
  namespace: $SECRETS_NAMESPACE
type: Opaque
data:
  tls.key: $ACME_PRIVATE_KEY